source 'https://github.com/CocoaPods/Specs.git'

target 'UIView-Screenshot', :exclusive => true do
  pod "UIView-Screenshot", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "UIView-Screenshot", :path => "../"

  
end
